# Numpy Practice Session

In [1]:
# pip install numpy
import numpy as np

In [2]:
food=np.array(["samosa","pakora","Raita"])
food

array(['samosa', 'pakora', 'Raita'], dtype='<U6')

In [3]:
prices=np.array([20,10,5])
prices

array([20, 10,  5])

In [4]:
type(prices)

numpy.ndarray

In [5]:
food[1]

'pakora'

In [6]:
prices.mean()

11.666666666666666

In [7]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
#empty
np.empty([5,1])

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(2, 20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [12]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [13]:
# Table
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [14]:
# Line Space 
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [15]:
# Specify  Data Type
print(np.ones(50,dtype=np.int64))

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1]


# Array Functions


In [16]:
a=np.array([10,12,15,3,4,8,3])
a

array([10, 12, 15,  3,  4,  8,  3])

In [17]:
a.sort()
a

array([ 3,  3,  4,  8, 10, 12, 15])

In [18]:
b=np.array([43, 23, 65,16, 46,55,22])
b

array([43, 23, 65, 16, 46, 55, 22])

In [19]:
c=np.concatenate((a,b))
c

array([ 3,  3,  4,  8, 10, 12, 15, 43, 23, 65, 16, 46, 55, 22])

In [20]:
c.sort()
c

array([ 3,  3,  4,  8, 10, 12, 15, 16, 22, 23, 43, 46, 55, 65])

# 2-D array

In [21]:
d=np.array([[12,56,23,22],[18,62,59,21]])
d

array([[12, 56, 23, 22],
       [18, 62, 59, 21]])

In [22]:
d[1,1]


62

In [23]:
d.sort()
d

array([[12, 22, 23, 56],
       [18, 21, 59, 62]])

In [24]:
e=np.array([[22,46,43],[48,12,39]])
e

array([[22, 46, 43],
       [48, 12, 39]])

In [25]:
# 

In [26]:
f=np.concatenate((d,e),axis=1) # axis 1 adding towards x axis side 
f                              # axis 1 adding towards vertical side

array([[12, 22, 23, 56, 22, 46, 43],
       [18, 21, 59, 62, 48, 12, 39]])

In [27]:
np.ndim(f)

2

In [28]:
f.size

14

In [29]:
f.shape

(2, 7)

In [30]:
g=np.linspace(1,5,24).reshape(2,3,4)
g

array([[[1.        , 1.17391304, 1.34782609, 1.52173913],
        [1.69565217, 1.86956522, 2.04347826, 2.2173913 ],
        [2.39130435, 2.56521739, 2.73913043, 2.91304348]],

       [[3.08695652, 3.26086957, 3.43478261, 3.60869565],
        [3.7826087 , 3.95652174, 4.13043478, 4.30434783],
        [4.47826087, 4.65217391, 4.82608696, 5.        ]]])

In [31]:
np.ndim(g)


3

In [32]:
g.shape

(2, 3, 4)

In [33]:
h=np.arange(7)
h

array([0, 1, 2, 3, 4, 5, 6])

In [34]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [35]:
a=a.reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [36]:
a=a.reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

  # Conver 1D to 2D 

In [37]:
x= np.array([1,2,3,4,5,6,7,8,9])


In [38]:
x.shape

(9,)

In [39]:
b=x[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [40]:
b.shape

(1, 9)

In [41]:
b=x[:,np.newaxis]
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [42]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [43]:
a[2:6]

array([], shape=(0, 3), dtype=int32)

In [1]:
import seaborn as sns
kashti=sns.load_dataset("titanic")
kashti.head(5)

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True