In [4]:
import numpy as np
e=np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [5]:
f=np.arange(0,10,2)
f

array([0, 2, 4, 6, 8])

In [15]:
g=np.arange(0,50,3)
print(g)
print(np.shape(g)) 
print(np.linspace(0,10,num=5))


[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]
(17,)
[ 0.   2.5  5.   7.5 10. ]


# Practice

In [ ]:
import numpy as np